displayName=Bank Equipment Stat Filter
author=Adam Giles,John Kryspin
support=
description=Adds a panel to search your bank for your best-in-slot equipment across all stats, and best stats across all slots
tags=bank,equipment,stat,filter,best in slot, bis
plugins=bankequipmentstatfilter.BankEquipmentStatFilterPlugin
build=standard